// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8DAz44MQNgY8FUe8tDrF7OxbH0xYxSdY',
    appId: '1:910189307949:web:b0e0511108dfc46fcc70a4',
    messagingSenderId: '910189307949',
    projectId: 'feepal-ebd7a',
    authDomain: 'feepal-ebd7a.firebaseapp.com',
    storageBucket: 'feepal-ebd7a.firebasestorage.app',
    measurementId: 'G-JZD8K4XK0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlRdStsCb1LLGjQFrPrHxDWy-njBnM2zE',
    appId: '1:910189307949:android:006fa6da2b6ca1a8cc70a4',
    messagingSenderId: '910189307949',
    projectId: 'feepal-ebd7a',
    storageBucket: 'feepal-ebd7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPr5Xrr8Izf6BhssRDhH1l_yVrrm4BXjw',
    appId: '1:910189307949:ios:48700def1e76bdf2cc70a4',
    messagingSenderId: '910189307949',
    projectId: 'feepal-ebd7a',
    storageBucket: 'feepal-ebd7a.firebasestorage.app',
    iosBundleId: 'com.example.mainDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPr5Xrr8Izf6BhssRDhH1l_yVrrm4BXjw',
    appId: '1:910189307949:ios:48700def1e76bdf2cc70a4',
    messagingSenderId: '910189307949',
    projectId: 'feepal-ebd7a',
    storageBucket: 'feepal-ebd7a.firebasestorage.app',
    iosBundleId: 'com.example.mainDart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8DAz44MQNgY8FUe8tDrF7OxbH0xYxSdY',
    appId: '1:910189307949:web:053afd2913b1eda9cc70a4',
    messagingSenderId: '910189307949',
    projectId: 'feepal-ebd7a',
    authDomain: 'feepal-ebd7a.firebaseapp.com',
    storageBucket: 'feepal-ebd7a.firebasestorage.app',
    measurementId: 'G-GBDHNLVXBZ',
  );
}
