import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Added
import 'firebase_options.dart'; // Added - generated by FlutterFire CLI
import 'loginscreen.dart';

void main() async {
  // 1. Ensure Flutter bindings are ready for async initialization
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase with the options from your CLI setup
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print("✅ FeePal Firebase: Connected Successfully");
  } catch (e) {
    print("❌ FeePal Firebase: Initialization Error: $e");
  }

  runApp(const FeePalApp());
}

class FeePalApp extends StatelessWidget {
  const FeePalApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'FeePal',
      theme: ThemeData(
        scaffoldBackgroundColor: Colors.white,
        splashColor: Colors.transparent,
        highlightColor: Colors.transparent,
        hoverColor: Colors.transparent,
        fontFamily: 'Inter',
      ),
      home: const SplashScreen(),
    );
  }
}

class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  void initState() {
    super.initState();
    // Delay for 3 seconds before navigating to the Welcome Screen
    Future.delayed(const Duration(seconds: 3), () {
      if (mounted) {
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(builder: (context) => const WelcomeScreen()),
        );
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: Center(child: Image.asset('assets/Feepal Logo.png')));
  }
}
